import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "TodoApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.JSX.Element;
}) {
  return (
    <html lang='en' data-theme='corporate'>
      <body className='h-screen'>
        <Header />
        {children}
      </body>
    </html>
  );
}
